<Project>
  <PropertyGroup Condition="'$(BepuRunnerBaseIntermediateOutputPath)' != ''">
    <BaseIntermediateOutputPath>$(BepuRunnerBaseIntermediateOutputPath)</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BepuRunnerBaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
